name: Security Checks

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  security-events: write

jobs:
  code-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
 
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python  # Change as per your project
 
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        
      - name: Fetch Code Scanning Alerts
        run: |
           curl -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Champmsecurity/juice-shop/code-scanning/alerts \
               -o code-scanning-alerts.json
      - name: Upload Code Scanning Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: code-scanning-alerts
          path: code-scanning-alerts.json

  secret-scanning:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: secret-scanning-custom-action
        uses: advanced-security/secret-scanning-tools@v1
        
      - name: Fetch Secret Scanning Alerts
        run: |
          curl -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/Champmsecurity/juice-shop/secret-scanning/alerts \
               -o secret-scanning-alerts.json
      - name: Upload Secret Scanning Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: secret-scanning-alerts
          path: secret-scanning-alerts.json

  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch Dependabot Alerts
        run: |
          echo "[]" > dependabot-alerts.json
          for page in {1..10}; do
            resp=$(curl -s -H "Authorization: token ${{secrets.PAT_TOKEN}}" \
              -H "Accept: application/vnd.github.v3+json" \
              "https://api.github.com/repos/Champmsecurity/juice-shop/dependabot/alerts?per_page=100&page=$page")
            count=$(echo "$resp" | jq length)
            if [ "$count" -eq 0 ]; then break; fi
            jq -s '.[0] + .[1]' dependabot-alerts.json <(echo "$resp") > tmp.json
            mv tmp.json dependabot-alerts.json
            if [ "$count" -lt 100 ]; then break; fi
          done
      - name: Upload Dependabot Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: dependabot-alerts
          path: dependabot-alerts.json
 
  combine-alerts:
    runs-on: ubuntu-latest
    needs: [code-scanning, secret-scanning, dependabot]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Download Code Scanning Alerts
        uses: actions/download-artifact@v4
        with:
          name: code-scanning-alerts

      - name: Download Secret Scanning Alerts
        uses: actions/download-artifact@v4
        with:
          name: secret-scanning-alerts

      - name: Download Dependabot Alerts
        uses: actions/download-artifact@v4
        with:
          name: dependabot-alerts

      - name: Combine All Alerts into One JSON
        run: |
          jq -n \
            --slurpfile code code-scanning-alerts.json \
            --slurpfile secret secret-scanning-alerts.json \
            --slurpfile dependabot dependabot-alerts.json \
            '{code_scanning: $code[0], secret_scanning: $secret[0], dependabot: $dependabot[0]}' \
            > all-alerts.json

      - name: Upload Combined Alerts
        uses: actions/upload-artifact@v4.6.2
        with:
          name: all-alerts
          path: all-alerts.json
      
      - name: Commit and push all-alerts.json
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add all-alerts.json
          git commit -m "Update all-alerts.json [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          
  zap-scan:
      runs-on: ubuntu-latest
      needs: [code-scanning, secret-scanning, dependabot]
      steps:
        - name: Run OWASP ZAP Baseline Scan
          uses: zaproxy/action-baseline@v0.10.0
          with:
            target: 'https://brokencrystal.com'
            fail_action: false
            allow_issue_writing: false

        - name: Upload ZAP Report
          uses: actions/upload-artifact@v4.6.2
          with:
            name: zap-report
            path: report_html.html
